name: CI-CD PIPELINE

on:
  push:
    branches: [main]

permissions:
  contents: write   # 🔥 VERY IMPORTANT

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Deploy to GitHub Pages
        run: |
          npm install
          git config --global user.email "rampradeepsamy@gmail.com"
          git config --global user.name "Rampradeep-K"
          npm run build
          npx gh-pages -d dist -b gh-pages
